---
- name: Deploy GPU Servers
  hosts: all
  become: yes
  become_user: root

  roles:
      - createusers
      - sudoers
      - nameserver_local
      - repo_local_7.6.1810
      - chrony
      - bashrc
      - motd
      - logrotate
      - rsyslog
      - route-vlan112
      - SELinux_Firewall_local
      - install_nvidia_grid_k2_driver
      - reboot
      - install_packages
      - zabbix
      - lldpd
      - ssh
      - change_root_pwd
