---
- name: Deploy Ceph-opennebula servers
  hosts: all
  become: yes
  become_user: root

  roles:
      - createusers
      - sudoers
      - chrony
      - bashrc
      - motd
      - nameserver_public
      - logrotate
      - reboot
      - update
      - install_packages
      - zabbix
      - lldpd
      - ssh
      - change_root_pwd