---
- name: Deploy Ubuntu servers
  hosts: all
  become: yes
  become_user: root

  roles:
      - update_ubuntu
      - createusers
      - sudoers
      - chrony_ubuntu
      - bashrc
      - motd_ubuntu
      - nameserver_public
      - logrotate
      - reboot
      - update_ubuntu
      - install_packages_ubuntu
      - lldpd
      - ssh
      - change_root_pwd