
- name: ListenIP for Zabbix-agent
  lineinfile:
   path: /etc/zabbix/zabbix_agentd.conf
   regexp: '^ServerActive'
   insertafter: '^ServerActive'
   line: ServerActive=10.10.12.30,10.10.21.0

- name: Restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
