
- name: ListenIP for Zabbix-agent
  lineinfile:
   path: /etc/zabbix/zabbix_agentd.conf
   regexp: '^ServerActive'
   insertafter: '^ServerActive'
   line: ServerActive=103.90.220.67

- name: Restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
