- name: copy grub file
  copy:
   src: grub
   dest: /etc/default/grub
   mode: '0644'

- name: copy blacklist.conf file
  copy:
   src: blacklist.conf
   dest: /etc/modprobe.d/blacklist.conf
   mode: '0644'
   
- name: update grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: install kernel-header, kernel-devel and dkms
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - kernel-headers
    - kernel-devel
    - dkms
    
- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present