- name: ensure a list of packages installed
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - bash-completion
    - vim
    - lshw
    - htop
    - wget
    - bwm-ng
    - net-tools
    - telnet
    - dmidecode